version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: personal_website_api_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: personal_website_db
      MYSQL_USER: personal_website_user
      MYSQL_PASSWORD: personal_website_pass
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: personal_website_api_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
      UPLOAD_LIMIT: 100M
    depends_on:
      - mysql

volumes:
  mysql_data: