"""add profile_photo_id to users

Revision ID: 32445a336ce9
Revises: 53c76b3819f8
Create Date: 2026-04-18 11:45:42.073509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32445a336ce9'
down_revision: Union[str, None] = '53c76b3819f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'images', ['profile_photo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'profile_photo_id')
    # ### end Alembic commands ###
