"""add image_id to projects

Revision ID: 79dc83d98544
Revises: fcf3a19e3889
Create Date: 2026-04-18 19:42:30.860543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79dc83d98544'
down_revision: Union[str, None] = 'fcf3a19e3889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_posts', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog_posts', 'images', ['cover_image_id'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'image_id')
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_column('blog_posts', 'cover_image_id')
    # ### end Alembic commands ###
