"""add blog_posts and blog_post_authors tables

Revision ID: eacde95d717c
Revises: 2cbd9c42606d
Create Date: 2026-04-18 12:07:15.948042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eacde95d717c'
down_revision: Union[str, None] = '2cbd9c42606d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reading_time', sa.Time(), nullable=True),
    sa.Column('visible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_deleted_at'), 'blog_posts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_user_id'), 'blog_posts', ['user_id'], unique=False)
    op.create_table('blog_post_authors',
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_post_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_post_authors')
    op.drop_index(op.f('ix_blog_posts_user_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_deleted_at'), table_name='blog_posts')
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
